let
    Source = SharePoint.Contents("", [ApiVersion = 15]),
    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
    General = #"Shared Documents"{[Name="General"]}[Content],
    #"Earned Hours" = General{[Name="Earned Hours"]}[Content],
    Robô = #"Earned Hours"{[Name="Robô"]}[Content],
    #"Earned Hours History" = Robô{[Name="Earned Hours History"]}[Content],
    #"Removed Other Columns" = Table.SelectColumns(#"Earned Hours History",{"Content", "Name"}),
    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Raw", each Csv.Document([Content], [Delimiter=";", Columns=31, Encoding=1252, QuoteStyle=QuoteStyle.None])),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Added Custom", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (4)", each #"Transform File (4)"([Content])),
    #"Expanded Raw" = Table.ExpandTableColumn(#"Invoke Custom Function1", "Raw", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31"}, {"Raw.Column1", "Raw.Column2", "Raw.Column3", "Raw.Column4", "Raw.Column5", "Raw.Column6", "Raw.Column7", "Raw.Column8", "Raw.Column9", "Raw.Column10", "Raw.Column11", "Raw.Column12", "Raw.Column13", "Raw.Column14", "Raw.Column15", "Raw.Column16", "Raw.Column17", "Raw.Column18", "Raw.Column19", "Raw.Column20", "Raw.Column21", "Raw.Column22", "Raw.Column23", "Raw.Column24", "Raw.Column25", "Raw.Column26", "Raw.Column27", "Raw.Column28", "Raw.Column29", "Raw.Column30", "Raw.Column31"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Raw",{"Content"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Data"}, {"Raw.Column1", "Ordem de Produção"}, {"Raw.Column2", "Item"}, {"Raw.Column3", "Status"}, {"Raw.Column4", "Quantidade"}, {"Raw.Column5", "8000(EST)"}, {"Raw.Column6", "8005(TRC)"}, {"Raw.Column7", "8006(TRT)"}, {"Raw.Column8", "8010(USI)"}, {"Raw.Column9", "8017(CXC)"}, {"Raw.Column10", "8020(MTG)"}, {"Raw.Column11", "8100(MTG A)"}, {"Raw.Column12", "8110(MTG C1)"}, {"Raw.Column13", "8120(MTG C2)"}, {"Raw.Column14", "8130(MTG D1)"}, {"Raw.Column15", "8140(MTG D2)"}, {"Raw.Column16", "8150(MTG F1)"}, {"Raw.Column17", "8160(MTG F3)"}, {"Raw.Column18", "8170(MTG G1)"}, {"Raw.Column19", "8180(MTG G2)"}, {"Raw.Column20", "8190(EMB)"}, {"Raw.Column21", "8200(CAR)"}, {"Raw.Column22", "1000"}, {"Raw.Column23", "1005"}, {"Raw.Column24", "1010"}, {"Raw.Column25", "1015"}, {"Raw.Column26", "1020"}, {"Raw.Column27", "1025"}, {"Raw.Column28", "1030"}, {"Raw.Column29", "1035"}, {"Raw.Column30", "1040"}, {"Raw.Column31", "Total"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"Transform File (4)"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Columns1", each ([Status] <> "" and [Status] <> "Status")),
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Ordem de Produção", Int64.Type}, {"Item", type text}, {"Status", type text}, {"Quantidade", Int64.Type}, {"8000(EST)", type number}, {"8005(TRC)", type number}, {"8006(TRT)", type number}, {"8010(USI)", type number}, {"8017(CXC)", type number}, {"8020(MTG)", type number}, {"8100(MTG A)", type number}, {"8110(MTG C1)", type number}, {"8120(MTG C2)", type number}, {"8130(MTG D1)", type number}, {"8140(MTG D2)", type number}, {"8150(MTG F1)", type number}, {"8160(MTG F3)", type number}, {"8170(MTG G1)", type number}, {"8180(MTG G2)", type number}, {"8190(EMB)", type number}, {"8200(CAR)", type number}, {"1000", type number}, {"1005", type number}, {"1010", type number}, {"1015", type number}, {"1020", type number}, {"1025", type number}, {"1030", type number}, {"1035", type number}, {"1040", type number}, {"Total", type number}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"Ordem de Produção", "Data", "Item", "Status", "Quantidade", "8000(EST)", "8005(TRC)", "8006(TRT)", "8010(USI)", "8017(CXC)", "8020(MTG)", "8100(MTG A)", "8110(MTG C1)", "8120(MTG C2)", "8130(MTG D1)", "8140(MTG D2)", "8150(MTG F1)", "8160(MTG F3)", "8170(MTG G1)", "8180(MTG G2)", "8190(EMB)", "8200(CAR)", "1000", "1005", "1010", "1015", "1020", "1025", "1030", "1035", "1040", "Total"}),
    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns",".txt","",Replacer.ReplaceText,{"Data"}),
    #"Inserted Replaced Text" = Table.AddColumn(#"Replaced Value", "Replaced Text", each Text.Start([Data], 2) & "/" & Text.Middle([Data], 2, 2) & "/" & Text.End([Data], 4), type text),
    #"Reordered Columns1" = Table.ReorderColumns(#"Inserted Replaced Text",{"Ordem de Produção", "Replaced Text", "Data", "Item", "Status", "Quantidade", "8000(EST)", "8005(TRC)", "8006(TRT)", "8010(USI)", "8017(CXC)", "8020(MTG)", "8100(MTG A)", "8110(MTG C1)", "8120(MTG C2)", "8130(MTG D1)", "8140(MTG D2)", "8150(MTG F1)", "8160(MTG F3)", "8170(MTG G1)", "8180(MTG G2)", "8190(EMB)", "8200(CAR)", "1000", "1005", "1010", "1015", "1020", "1025", "1030", "1035", "1040", "Total"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns1",{{"Replaced Text", type date}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type1",{"Data"})
in
    #"Removed Columns2"