let
    Source = SharePoint.Contents("", [ApiVersion = 15]),
    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
    General = #"Shared Documents"{[Name="General"]}[Content],
    #"Earned Hours" = General{[Name="Earned Hours"]}[Content],
    Robô = #"Earned Hours"{[Name="Robô"]}[Content],
    #"Earned Hours History" = Robô{[Name="Earned Hours History"]}[Content],
    #"Removed Other Columns" = Table.SelectColumns(#"Earned Hours History",{"Content", "Name"}),
    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Raw", each Csv.Document([Content], [Delimiter=";", Columns=31, Encoding=1252, QuoteStyle=QuoteStyle.None])),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Headers", each Table.PromoteHeaders([Raw])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom1",{"Name", "Headers"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns1",{{"Name", "Data"}}),
    #"Expanded Headers" = Table.ExpandTableColumn(#"Renamed Columns", "Headers", {"", "_1", "_2", "_3", "_4", "_5", "_6", "_7", "_8", "_9", "_10", "_11", "_12", "_13", "_14", "_15", "_16", "_17", "_18", "_19", "_20", "_21", "_22", "_23", "_24", "_25", "_26", "_27", "_28", "_29"}, {"Column1", "_1", "_2", "_3", "_4", "_5", "_6", "_7", "_8", "_9", "_10", "_11", "_12", "_13", "_14", "_15", "_16", "_17", "_18", "_19", "_20", "_21", "_22", "_23", "_24", "_25", "_26", "_27", "_28", "_29"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Expanded Headers",{{"Column1", "Item"}, {"_1", "Status"}, {"_2", "Quantidade"}, {"_3", "8000(EST)"}, {"_4", "8005(TRC)"}, {"_5", "8006(TRT)"}, {"_6", "8010(USI)"}, {"_7", "8017(CXC)"}, {"_8", "8020(MTG)"}, {"_9", "8100(MTG A)"}, {"_10", "8110(MTG C1)"}, {"_11", "8120(MTG C2)"}, {"_12", "8130(MTG D1)"}, {"_13", "8140(MTG D2)"}, {"_14", "8150(MTG F1)"}, {"_15", "8160(MTG F3)"}, {"_16", "8170(MTG G1)"}, {"_17", "8180(MTG G2)"}, {"_18", "8190(EMB)"}, {"_19", "8200(CAR)"}, {"_20", "1000"}, {"_21", "1005"}, {"_22", "1010"}, {"_23", "1015"}, {"_24", "1020"}, {"_25", "1025"}, {"_26", "1030"}, {"_27", "1035"}, {"_28", "1040"}, {"_29", "Total"}}),
    #"Removed Top Rows" = Table.Skip(#"Renamed Columns3",1),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Top Rows",{{"Data", type text}, {"Item", type text}, {"Status", type text}, {"Quantidade", Int64.Type}, {"8000(EST)", type number}, {"8005(TRC)", type number}, {"8006(TRT)", type number}, {"8010(USI)", type number}, {"8017(CXC)", type number}, {"8020(MTG)", type number}, {"8100(MTG A)", type number}, {"8110(MTG C1)", type number}, {"8120(MTG C2)", type number}, {"8130(MTG D1)", type number}, {"8140(MTG D2)", type number}, {"8150(MTG F1)", type number}, {"8160(MTG F3)", type number}, {"8170(MTG G1)", type number}, {"8180(MTG G2)", type number}, {"8190(EMB)", type number}, {"8200(CAR)", type number}, {"1000", type number}, {"1005", type number}, {"1010", type number}, {"1015", type number}, {"1020", type number}, {"1025", type number}, {"1030", type number}, {"1035", type number}, {"1040", type number}, {"Total", type number}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"Item", "Data", "Status", "Quantidade", "8000(EST)", "8005(TRC)", "8006(TRT)", "8010(USI)", "8017(CXC)", "8020(MTG)", "8100(MTG A)", "8110(MTG C1)", "8120(MTG C2)", "8130(MTG D1)", "8140(MTG D2)", "8150(MTG F1)", "8160(MTG F3)", "8170(MTG G1)", "8180(MTG G2)", "8190(EMB)", "8200(CAR)", "1000", "1005", "1010", "1015", "1020", "1025", "1030", "1035", "1040", "Total"}),
    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns",".txt","",Replacer.ReplaceText,{"Data"}),
    #"Trimmed Text" = Table.TransformColumns(#"Replaced Value",{{"Data", Text.Trim, type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Trimmed Text", each ([Status] <> "Status")),
    #"Reordered Columns1" = Table.ReorderColumns(#"Filtered Rows",{"Item","Data", "Status", "Quantidade", "8000(EST)", "8005(TRC)", "8006(TRT)", "8010(USI)", "8017(CXC)", "8020(MTG)", "8100(MTG A)", "8110(MTG C1)", "8120(MTG C2)", "8130(MTG D1)", "8140(MTG D2)", "8150(MTG F1)", "8160(MTG F3)", "8170(MTG G1)", "8180(MTG G2)", "8190(EMB)", "8200(CAR)", "1000", "1005", "1010", "1015", "1020", "1025", "1030", "1035", "1040", "Total"}),
    #"Added Custom2" = Table.AddColumn(#"Reordered Columns1", "Custom", each Text.From([Data]) & "/" & Text.Range(Text.From([Data]), 5, 2) & ""/"" & Text.Range(Text.From([Data]), 7, 4)),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom2",{"Custom"}),
    #"Inserted Replaced Text" = Table.AddColumn(#"Removed Columns1", "New Date", each Text.Start([Data], 2) & "/" & Text.Middle([Data], 2, 2) & "/" & Text.End([Data], 4), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Inserted Replaced Text",{"Data"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"New Date", "Data"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Data", type date}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Changed Type1",{"Item", "Data", "Status", "Quantidade", "8000(EST)", "8005(TRC)", "8006(TRT)", "8010(USI)", "8017(CXC)", "8020(MTG)", "8100(MTG A)", "8110(MTG C1)", "8120(MTG C2)", "8130(MTG D1)", "8140(MTG D2)", "8150(MTG F1)", "8160(MTG F3)", "8170(MTG G1)", "8180(MTG G2)", "8190(EMB)", "8200(CAR)", "1000", "1005", "1010", "1015", "1020", "1025", "1030", "1035", "1040", "Total"})
in
    #"Reordered Columns2"